sonar.projectKey=A-leks-andr_Calculator
sonar.organization=a-leks-andr


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Calculator
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=calculator_logic.py
sonar.python.version=3.14

sonar.tests=/tests
sonar.python.coverage.reportPaths=coverage.xml

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8